# Generated by Django 2.2.5 on 2019-09-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модели принтеров',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, max_length=32, verbose_name='Серийный номер')),
                ('name', models.CharField(default='Printer', max_length=64, verbose_name='Наименование')),
                ('page_count_total', models.PositiveIntegerField(default=0, verbose_name='Счетчик отпечатков общий')),
                ('page_count_color', models.PositiveIntegerField(default=0, verbose_name='Счетчик цветных отпечатков')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.Model', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='PrinterCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_getting', models.DateField(verbose_name='Дата показателей')),
                ('page_count_total', models.PositiveIntegerField(default=0, verbose_name='Счетчик отпечатков общий')),
                ('page_count_color', models.PositiveIntegerField(default=0, verbose_name='Счетчик цветных отпечатков')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.Printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Счетчики принтера',
                'verbose_name_plural': 'Счетчики принтеров',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.Model', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Запчасть принтера',
                'verbose_name_plural': 'Запчасти принтеров',
            },
        ),
    ]
